### ISSUE TITLE
Error finding ~flexboxgrid

### ISSUE THREAD

**Issue by rsteckler** [roylee0704/react-flexbox-grid#12]
I'm relatively new to Webpack and have a hunch that my problem is in my webpack config.  I know you're not Webpack support, but hoping you can point me in the right direction.

Here's the error:
```
ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]_[hash:base64:3]!./~/postcss-loader!./~/react-flexbox-grid/lib/style.scss
    Module build failed: Error: /Users/ryan/code/test/web/node_modules/react-flexbox-grid/lib/style.scss:1:1: Failed to find '~flexboxgrid' from /Users/ryan/code/test/web
```

The referenced /Users/ryan/code/test/web/node_modules/react-flexbox-grid/lib/style.scss has this:
```
@import '~flexboxgrid';
```

My webpack.config has this:
```
        test: /\.scss$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${DEBUG ? 'sourceMap&' : 'minimize&'}modules&localIdentName=` +
          `${DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]'}`,
          'postcss-loader',
        ],
```

Any help would be massively appreciated!

**Comment by roylee0704** [comment]
@rsteckler  Have you checked my https://github.com/roylee0704/react-flexbox-grid-example  already? :) Over there I've put an example of how to run & supercharge my lib with webpack.

**Comment by rsteckler** [comment]
I looked at the example and it works perfectly  :)

I even tried stealing pieces of the webpack config from your project, but I'm unable to find the right magical combination to get it working.  

I think the real problem is that I don't understand what that error is telling me.  ~flexboxgrid seems like an odd path to be looking for - it's clearly not referencing my user directory (~).  I'm assuming it's looking in the node_modules folder, but in that case, it should find flexboxgrid;  it's definitely installed.

I read the docs for isomorphic-style-loader, but didn't see anything that points me in the right direction, either.

I totally get that your example proves that react-flexbox-grid works!  I'm just trying to get it to work in the project I already have setup  :)

**Comment by roylee0704** [comment]
ah, if that's the case, would you mind to paste your webpack.config & package.json here? :)

**Comment by rsteckler** [comment]
Absolutely; pasted below.  For what it's worth, I've basically taken [this project](https://github.com/kriasoft/react-starter-kit) and tried to add react-flexbox-grid to it.
I know this isn't a problem in this project, so I appreciate the help!
```
/**
 * React Starter Kit (https://www.reactstarterkit.com/)
 *
 * Copyright © 2014-2016 Kriasoft, LLC. All rights reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.txt file in the root directory of this source tree.
 */

import path from 'path';
import webpack from 'webpack';
import extend from 'extend';
import AssetsPlugin from 'assets-webpack-plugin';

const DEBUG = !process.argv.includes('--release');
const VERBOSE = process.argv.includes('--verbose');
const AUTOPREFIXER_BROWSERS = [
  'Android 2.3',
  'Android >= 4',
  'Chrome >= 35',
  'Firefox >= 31',
  'Explorer >= 9',
  'iOS >= 7',
  'Opera >= 12',
  'Safari >= 7.1',
];
const GLOBALS = {
  'process.env.NODE_ENV': DEBUG ? '"development"' : '"production"',
  __DEV__: DEBUG,
};

//
// Common configuration chunk to be used for both
// client-side (client.js) and server-side (server.js) bundles
// -----------------------------------------------------------------------------

const config = {
  output: {
    publicPath: '/',
    sourcePrefix: '  ',
  },

  cache: DEBUG,
  debug: DEBUG,

  stats: {
    colors: true,
    reasons: DEBUG,
    hash: VERBOSE,
    version: VERBOSE,
    timings: true,
    chunks: VERBOSE,
    chunkModules: VERBOSE,
    cached: VERBOSE,
    cachedAssets: VERBOSE,
  },

  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
  ],

  resolve: {
    extensions: ['', '.scss', '.webpack.js', '.web.js', '.js', '.jsx', '.json'],
  },

  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        include: [
          path.resolve(__dirname, '../node_modules/react-routing/src'),
          path.resolve(__dirname, '../src'),
        ],
        loader: 'babel-loader',
      }, {
        test: /\.scss$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${DEBUG ? 'sourceMap&' : 'minimize&'}modules&localIdentName=` +
          `${DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]'}`,
          'postcss-loader',
        ],
      }, {
        test: /\.json$/,
        loader: 'json-loader',
      }, {
        test: /\.txt$/,
        loader: 'raw-loader',
      }, {
        test: /\.(png|jpg|jpeg|gif|svg|woff|woff2)$/,
        loader: 'url-loader?limit=10000',
      }, {
        test: /\.(eot|ttf|wav|mp3)$/,
        loader: 'file-loader',
      },
    ],
  },

  postcss: function plugins(bundler) {
    return [
      require('postcss-import')({ addDependencyTo: bundler }),
      require('precss')(),
      require('autoprefixer')({ browsers: AUTOPREFIXER_BROWSERS }),
    ];
  },
};

//
// Configuration for the client-side bundle (client.js)
// -----------------------------------------------------------------------------

const clientConfig = extend(true, {}, config, {
  entry: './src/client.js',
  output: {
    path: path.join(__dirname, '../build/public'),
    filename: DEBUG ? '[name].js?[hash]' : '[name].[hash].js',
  },

  // Choose a developer tool to enhance debugging
  // http://webpack.github.io/docs/configuration.html#devtool
  devtool: DEBUG ? 'cheap-module-eval-source-map' : false,
  plugins: [
    new webpack.DefinePlugin(GLOBALS),
    new AssetsPlugin({
      path: path.join(__dirname, '../build'),
      filename: 'assets.js',
      processOutput: x => `module.exports = ${JSON.stringify(x)};`,
    }),
    ...(!DEBUG ? [
      new webpack.optimize.DedupePlugin(),
      new webpack.optimize.UglifyJsPlugin({
        compress: {
          // jscs:disable requireCamelCaseOrUpperCaseIdentifiers
          screw_ie8: true,

          // jscs:enable requireCamelCaseOrUpperCaseIdentifiers
          warnings: VERBOSE,
        },
      }),
      new webpack.optimize.AggressiveMergingPlugin(),
    ] : []),
  ],
});

//
// Configuration for the server-side bundle (server.js)
// -----------------------------------------------------------------------------

const serverConfig = extend(true, {}, config, {
  entry: './src/server.js',
  output: {
    path: './build',
    filename: 'server.js',
    libraryTarget: 'commonjs2',
  },
  target: 'node',
  externals: [
    /^\.\/assets$/,
    function filter(context, request, cb) {
      const isExternal =
        request.match(/^[@a-z][a-z\/\.\-0-9]*$/i) &&
        !request.match(/^react-routing/) &&
        !context.match(/[\\/]react-routing/);
      cb(null, Boolean(isExternal));
    },
  ],
  node: {
    console: false,
    global: false,
    process: false,
    Buffer: false,
    __filename: false,
    __dirname: false,
  },
  devtool: 'source-map',
  plugins: [
    new webpack.DefinePlugin(GLOBALS),
    new webpack.BannerPlugin('require("source-map-support").install();',
      { raw: true, entryOnly: false }),
  ],
});

export default [clientConfig, serverConfig];
```

```{
  "private": true,
  "engines": {
    "node": ">=5.0 <6",
    "npm": ">=3.3 <4"
  },
  "dependencies": {
    "babel-polyfill": "^6.3.14",
    "babel-runtime": "^6.3.19",
    "bluebird": "3.1.4",
    "classnames": "2.2.3",
    "eventemitter3": "1.1.1",
    "express": "4.13.4",
    "fastclick": "1.0.6",
    "fbjs": "0.6.1",
    "flexboxgrid": "^6.3.0",
    "front-matter": "2.0.5",
    "history": "2.0.0-rc2",
    "isomorphic-style-loader": "0.0.7",
    "jade": "1.11.0",
    "material-ui": "^0.14.2",
    "node-fetch": "1.3.3",
    "normalize.css": "3.0.3",
    "react": "0.14.6",
    "react-dom": "0.14.6",
    "react-flexbox-grid": "^0.9.2",
    "react-routing": "0.0.7",
    "sass-loader": "^3.1.2",
    "source-map-support": "0.4.0",
    "whatwg-fetch": "0.11.0"
  },
  "devDependencies": {
    "assets-webpack-plugin": "^3.2.0",
    "autoprefixer": "^6.3.1",
    "babel-cli": "^6.4.5",
    "babel-eslint": "^5.0.0-beta6",
    "babel-loader": "^6.2.1",
    "babel-plugin-react-transform": "^2.0.0",
    "babel-plugin-transform-runtime": "^6.4.3",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "browser-sync": "^2.11.1",
    "css-loader": "^0.23.1",
    "csscomb": "^3.1.8",
    "del": "^2.2.0",
    "eslint": "^1.10.3",
    "eslint-config-airbnb": "^4.0.0",
    "eslint-loader": "^1.2.0",
    "eslint-plugin-react": "^3.15.0",
    "extend": "^3.0.0",
    "file-loader": "^0.8.5",
    "gaze": "^0.5.2",
    "git-repository": "^0.1.1",
    "glob": "^6.0.4",
    "jest-cli": "^0.8.2",
    "jscs": "^2.8.0",
    "json-loader": "^0.5.4",
    "mkdirp": "^0.5.1",
    "ncp": "^2.0.0",
    "postcss": "^5.0.14",
    "postcss-import": "^7.1.3",
    "postcss-loader": "^0.8.0",
    "precss": "^1.4.0",
    "raw-loader": "^0.5.1",
    "react-transform-catch-errors": "^1.0.1",
    "react-transform-hmr": "^1.0.1",
    "redbox-react": "^1.2.0",
    "replace": "^0.3.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.11",
    "webpack-hot-middleware": "^2.6.0",
    "webpack-middleware": "^1.4.0"
  },
  "jest": {
    "rootDir": "./src",
    "scriptPreprocessor": "../preprocessor.js",
    "unmockedModulePathPatterns": [
      "fbjs",
      "react"
    ]
  },
  "scripts": {
    "lint": "eslint src tools && jscs src tools",
    "csslint": "csscomb src/components --lint --verbose",
    "csscomb": "csscomb src/components --verbose",
    "test": "eslint src && jest",
    "clean": "babel-node tools/run clean",
    "copy": "babel-node tools/run copy",
    "bundle": "babel-node tools/run bundle",
    "build": "babel-node tools/run build",
    "deploy": "babel-node tools/run deploy",
    "start": "babel-node tools/run start"
  }
}
```

**Comment by roylee0704** [comment]
perhaps the culprit is the missing extension: `\.css` for `css-loader`.  

```js
{
        test: /(\.scss|\.css)$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${DEBUG ? 'sourceMap&' : 'minimize&'}modules&localIdentName=` +
          `${DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]'}`,
          'postcss-loader',
        ],
      },
```

**Comment by leandroz** [comment]
I also had the same problem, I solved it adding .scss to the require statement for the style file. I think you should do the same to save some headaches to other people! By the way thanks for the library! great work!

**Comment by rsteckler** [comment]
Adding the css loader didn't make a difference.  
I edited the /node_modules/react-flexbox-grid/lib/styles.scss file that had the "problematic" import.  I changed it from:
```
@import '~flexboxgrid';
```
to
```
@import 'flexboxgrid/dist/flexboxgrid.css';
```

Things look "better", but I still get a weird exception in webpack:
```
Child
    Time: 5102ms
                           Asset     Size  Chunks             Chunk Names
    main.js?221d13c9b7b647724618  4.19 MB       0  [emitted]  main
Child
    Time: 4219ms
            Asset    Size  Chunks             Chunk Names
        server.js  206 kB       0  [emitted]  main
    server.js.map  209 kB       0  [emitted]  main
webpack: bundle is now VALID.
Error: Cannot find module '../style'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/rsteckler/code/evmote/web/node_modules/react-flexbox-grid/lib/components/Grid.js:13:14)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

This is after I included '.scss' in the list of resolve extensions in the webpack config.

I changed react-flexbox-grid/lib/componenets/Grid.js to say:
```
var _style = require('../style.scss');
```

...but that resulted in another error:
```
Child
    Time: 4079ms
            Asset    Size  Chunks             Chunk Names
        server.js  206 kB       0  [emitted]  main
    server.js.map  209 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/rsteckler/code/evmote/web/node_modules/react-flexbox-grid/lib/components/Grid.js:13:14)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
webpack built a514d96197abd778897b in 175ms
```

I'm guessing that modifying the compiled code in lib isn't a great idea, but I'm getting desperate  :)

**Comment by roylee0704** [comment]
okay, revert back to its previous state, and add `.css` extension into loaders:

```js
      {
        test: /(\.scss|\.css)$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${DEBUG ? 'sourceMap&' : 'minimize&'}modules&localIdentName=` +
          `${DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]'}`,
          'postcss-loader',
        ],
      },
```

Then, add `modulesDirectories` under `resolve:`, this tells webpack where to consume files.
```js
  resolve: {
    extensions: ['', '.jsx', '.css', '.scss', '.js', '.json'],
    modulesDirectories: [
      'node_modules',
      path.resolve(__dirname, './node_modules')
    ]
  },
```

**Comment by rsteckler** [comment]
Thank you for the help.  When I do that, I continue to get:
```
ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]_[hash:base64:3]!./~/postcss-loader!./~/react-flexbox-grid/lib/style.scss
    Module build failed: Error: /Users/rsteckler/code/evmote/web/node_modules/react-flexbox-grid/lib/style.scss:1:1: Failed to find '~flexboxgrid' from /Users/rsteckler/code/evmote/web
```

Simply getting rid of the ~ on the import statement gives me:
```
Child
    Time: 5146ms
                           Asset     Size  Chunks             Chunk Names
    main.js?221d13c9b7b647724618  4.19 MB       0  [emitted]  main
Child
    Time: 4202ms
            Asset    Size  Chunks             Chunk Names
        server.js  206 kB       0  [emitted]  main
    server.js.map  209 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
Error: Cannot find module '../style'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/rsteckler/code/evmote/web/node_modules/react-flexbox-grid/lib/components/Grid.js:13:14)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
webpack built 221d13c9b7b647724618 in 183ms
Child
    Time: 183ms
Child
    Time: 4202ms
            Asset    Size  Chunks             Chunk Names
        server.js  206 kB       0  [emitted]  main
    server.js.map  209 kB       0  [emitted]  main
webpack: bundle is now VALID.
Error: Cannot find module '../style'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/rsteckler/code/evmote/web/node_modules/react-flexbox-grid/lib/components/Grid.js:13:14)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

If you get fed up trying to help, let me know.  You're under no obligation to get it working  :)

**Comment by roylee0704** [comment]
No worries, I'm more than willing to help. I will attempt to include `react-flexbox-grid` into `react-starter-kit`, when I get back to my machine tomorrow.  :)

**Comment by rsteckler** [comment]
That would be AMAZING.

Thank you!

On Wed, Jan 27, 2016 at 11:36 AM LEE SIONG TAI (Roy) <
notifications@github.com> wrote:

> No worries, I'm more than willing to help. I will attempt to include
> react-flexbox-grid into react-starter-kit, when I get back to my machine
> tomorrow. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roylee0704/react-flexbox-grid/issues/12#issuecomment-175814375>
> .
>
-- 

Thanks,
Ryan Steckler

**Comment by leandroz** [comment]
I made it work with https://github.com/davezuko/react-redux-starter-kit adding the .scss extension as I said before. The only thing I don't understand why the change made it work, I have the '' to resolve files without the extension.

**Comment by rsteckler** [comment]
@leandroz Adding the extension didn't work for me.  I definitely tried that.  
My guess is that it's something with the isomorphic-style-loader not liking the way the modules are required, but I'm way out of my depth on this stuff.  Still in learning mode with react/webpack.

**Comment by roylee0704** [comment]
@rsteckler  cant get it to work with isomophic-style-loader. I'm gonna try on different approach.

**Comment by rsteckler** [comment]
Well, I'm glad it wasn't just me  :)
I'm going to try a  different boilerplate that works better with flexbox-grid.  There's no need to spend more time trying to get them working together.

Thanks for all of your help!

**Comment by rsteckler** [comment]
I just tried it with [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) and it works perfectly.

Thank again!
