### ISSUE TITLE
Unexpected token .

### ISSUE THREAD

**Issue by iammarkps** [roylee0704/react-flexbox-grid#160]
When I use react-flexbox-grid with my project. It throw this error

```
SyntaxError: Unexpected token .
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/iammark/Projects/openhouse/node_modules/react-flexbox-grid/lib/classNames.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

Step to reproduce
1. Clone this repo https://github.com/iammarkps/openhouse
2. yarn install
3. yarn dev

**Comment by wilsonarizaArable** [comment]
Having same issue, will have to use another library
